### ISSUE TITLE
Add option to return part-of children in queries

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-ui#102]
This could be a checkbox option on the results page

**Comment by balhoff** [comment]
This is implemented for anatomical structure pages:

http://kb.phenoscape.org/#/entity/http://purl.obolibrary.org/obo/UBERON_0012353?tab=taxa&taxatab=phenotypes&genestab=phenotypes&filters.phenotypesTaxaIncludeParts=true

and taxon phenotype pages:

http://kb.phenoscape.org/#/taxon/http://purl.obolibrary.org/obo/VTO_0059975?tab=phenotypes&phenotypes.entity_parts=true&phenotypes.quality_type=quality-phenotype&phenotypes.entity=http:%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0012353

**Comment by wdahdul** [comment]
+1
