### ISSUE TITLE
inconsistent queries with part_of relation

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-ui#103]
Queries currently shouldn't return parts, but this happens for some terms (for example, 'cranium' returns annotations to parts of cranium as well as the term itself). Queries on 'forelimb skeleton' and 'dorsal fin skeleton' don't return annotations to parts. 

(as a side note, issue #102 requests a checkbox that when clicked returns part-of children in queries)

**Comment by balhoff** [comment]
I think this is stemming from some bad interactions with logical definitions from HP or MP. I haven't fully verified this though. I have some ideas for insulating the rest of the system from these effects (like forcing mouse and human phenotypes to only apply to mice or human; currently they are defined "globally").

**Comment by pmabee** [comment]
I wonder if Chris could help with this if it is an ontology issue?

**Comment by balhoff** [comment]
I think the situation for this is improved now, although there will always be ontology integration challenges. Those will be ongoing though.
