### ISSUE TITLE
Add include homologs to phenotype query

### ISSUE THREAD

**Issue by balhoff** [phenoscape/phenoscape-kb-ui#106]

**Comment by wdahdul** [comment]
Paula and I are confirming this item, and we think a check box next to or below the query box would look fine.

**Comment by balhoff** [comment]
Need to check that homology relationships are shown in the properties panel. `tympanic ring` should be homologous to `angular bone`. Need to bring in annotation axioms from RO, which include some missing property labels.

**Comment by balhoff** [comment]
The queries are implemented now. Compare `angular bone` and `tympanic ring` search results for taxa and genes, with and without homology:

[angular bone](http://kb.phenoscape.org/#/entity/http://purl.obolibrary.org/obo/UBERON_0011079?tab=taxa&taxatab=phenotypes&genestab=phenotypes)

[tympanic ring](http://kb.phenoscape.org/#/entity/http://purl.obolibrary.org/obo/UBERON_0002218?tab=taxa&taxatab=phenotypes&genestab=phenotypes)

**Comment by balhoff** [comment]
I added missing annotation axioms from RO into the KB (we don't load all of RO because of reasoning problems) and now the homology relationships show up with labels in the Properties tab.

@wdahdul I am going to close this issue since it was implemented according to the issue, but please open another ticket if there are requests for changes/additional features.
