### ISSUE TITLE
change Properties tab to Semantics

### ISSUE THREAD

**Issue by balhoff** [phenoscape/phenoscape-kb-ui#109]
Discussion with Todd and Hilmar resulted in the idea to change the Properties tab label to "Semantics". For example, [here](http://kb.phenoscape.org/#/entity/http://purl.obolibrary.org/obo/UBERON_0002513?tab=properties&taxatab=phenotypes&genestab=phenotypes) and [here](http://kb.phenoscape.org/#/taxon/http://purl.obolibrary.org/obo/VTO_0036225?phenotypes.quality_type=quality-phenotype&tab=properties&phenotypes.entity_parts=false&phenotypes.entity_homologs=false)

@wdahdul @pmabee do you have any thoughts on this?

**Comment by wdahdul** [comment]
I think something like "overview" or "summary" might be more appropriate, and in keeping with current mockups (slide 1) in which the term info page displays a variety of information and links, such as the definition, synonyms, relationships (tree view), links to Kb data, and widget visualizations.

**Comment by balhoff** [comment]
Obsolete in new UI.
