### ISSUE TITLE
Display phenoscape homologies in Properties

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-ui#113]
Requires a service to return homologies linked to taxa
Simplify display to: ‘homologous to’ and ‘serially homologous to’
Add popup box with evidence and attribution, e.g., angular bone in Teleostei (Smith 2016)

**Comment by balhoff** [comment]
This is done; I just realized I didn't put the attribution stuff in a popup box. What do you think? Should I move it? cc @pmabee 

Here's an example: [manual digit](http://kb.phenoscape.org/#/entity/http://purl.obolibrary.org/obo/UBERON_0002389?tab=properties&taxatab=phenotypes&genestab=phenotypes)

**Comment by wdahdul** [comment]
closing this one; note that I added issue #129  for the source and evidence popup box.
