### ISSUE TITLE
Add check box for serial homology

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-ui#114]
In the Taxa tab, add checkbox to filter results on serial homology (in addition to historical homology)

**Comment by balhoff** [comment]
Current query includes both, but these need to separated.

**Comment by balhoff** [comment]
Fixed by f54a51c4443da4dfb2f12cec35ac776ea74fdc4f and https://github.com/phenoscape/phenoscape-kb-services/commit/23d5899f8e3f49537763c86ad7827c27ac653295
