### ISSUE TITLE
Feedback button comment box

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-ui#121]
Add popup comment box for the Feedback button, with fields for "name", "email address", and "comments" that can be filled and submitted directly from the KB page.  Clicking on feedback currently takes you to the phenoscape UI github, which might deter users unfamiliar with github (they also need to create a github account to add items).

**Comment by wdahdul** [comment]
![screen shot 2017-08-07 at 3 40 36 pm 2](https://user-images.githubusercontent.com/957012/29048723-f99b6614-7b86-11e7-9446-ea8145cbed4f.png)

**Comment by balhoff** [comment]
@wdahdul @pmabee @hlapp I set up a Google Forms link to allow users to submit feedback without logging into anything. This allows us to not need to run a service which sends emails, which can be a bit of a security headache. You can try it from the Feedback link on any KB page. I can also provide access to the feedback submissions spreadsheet to any of you.
