### ISSUE TITLE
Combine ‘Presence’ and ‘Absence’ phenotypes with ‘Phenotypes’

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-ui#126]
Remove the separate tabs for 'presence' and 'absence' and combine them with other phenotypes in "phenotypes" tab.

**Comment by wdahdul** [comment]
See also  #110

**Comment by wdahdul** [comment]
Also, distinguish inferred vs. asserted annotations with, for example, different font colors.

**Comment by balhoff** [comment]
See https://github.com/phenoscape/phenoscape-kb-web-ui/issues/13
