### ISSUE TITLE
Edits to the "Match details" display 

### ISSUE THREAD

**Issue by prashanti** [phenoscape/phenoscape-kb-ui#15]
Should change "Gene profile" to "Query gene" and "Taxon profile" to "Matched taxon". Also, maybe change "Profile size" to "Number of phenotypes".

**Comment by prashanti** [comment]
Also, change "Score" in the "Match details" display to "Information Content".

**Comment by balhoff** [comment]
Implemented in d75c3cd8755f3d80e889bd6ca5911abc338ed200.
