### ISSUE TITLE
Add text for pop-up on IC warning

### ISSUE THREAD

**Issue by prashanti** [phenoscape/phenoscape-kb-ui#19]
Something like "This match was found to be more informative among taxa than genes." Thoughts?@pmabee @hlapp @balhoff @tjv

**Comment by balhoff** [comment]
I used this text:
"This match was found to be informative among taxa; however, it is relatively common among gene annotations."

Implemented in 2c59a74986329386a67f9206ed59a46fcb29978f.

**Comment by prashanti** [comment]
We will have to add text about the disparity threshold and the proportion of MICAs for which warnings will be generated with this threshold. I will give you this text after I get the disparity scores for all MICAs.
