### ISSUE TITLE
Add the MICA to the detailed display. 

### ISSUE THREAD

**Issue by prashanti** [phenoscape/phenoscape-kb-ui#24]

**Comment by prashanti** [comment]
"Most Informative Common Subsumer" should be "Most Informative Common Ancestor (MICA)" to be consistent with the manuscript. @balhoff

**Comment by balhoff** [comment]
Does anyone have a strong preference for the term "ancestor"? I am not a fan of the parent/child/ancestor terminology for ontology concepts. I think they are more understandable as overlapping (or not) sets.
cc @tjv @hlapp @pmabee

**Comment by hlapp** [comment]
> Does anyone have a strong preference for the term "ancestor"? I am not a fan of the parent/child/ancestor terminology for ontology concepts. I think they are more understandable as overlapping (or not) sets.

I agree, and for that reason do actually think that subsumer is the better term. That said, ancestor _is_ in use for ontologies, too, and at the end of the day what's most important is to be consistent.

**Comment by prashanti** [comment]
I also prefer the term subsumer over ancestor but in our case MICA is the appropriate and commonly used term to describe the subsumers contributing to the median similarity.

**Comment by balhoff** [comment]
Done.
