### ISSUE TITLE
Create landing page for phenotype terms

### ISSUE THREAD

**Issue by balhoff** [phenoscape/phenoscape-kb-ui#30]
Currently anatomical entities, taxa, and genes can all be traversed to detail pages of their own. Need to create a version for phenotype terms.

**Comment by wdahdul** [comment]
Jim, is this referring to the phenotype tab, or phenotype popup box?

**Comment by balhoff** [comment]
I originally envisioned a page per phenotype. But we decided together to morph this into the popup box idea.

**Comment by balhoff** [comment]
This is now covered by #105 .
