### ISSUE TITLE
Add part_of to Gene expression text

### ISSUE THREAD

**Issue by pmabee** [phenoscape/phenoscape-kb-ui#35]
Change "These genes have been annotated with expression locations within [entity](directly or via inference)." to "These genes have been annotated with expression locations within or part of [entity](directly or via inference). (see e.g.,: http://kb.phenoscape.org/#/entity/http://purl.obolibrary.org/obo/UBERON_0000151)

**Comment by balhoff** [comment]
Fixed by 77182118cdffb213fa13a8cf33d2de4b196b9a99.
