### ISSUE TITLE
Matching term name in search results

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-ui#39]
The search results for entity sometimes contains terms that don't match the search string. For example, searching on "supraorbital bone" results in:

supraorbital bone
supra-orbital ridge

The second term doesn't seem to have "supraorbital bone" as a synonym, so not sure why it appears in the results?

**Comment by balhoff** [comment]
The search uses a 3rd party text indexer and is somewhat fuzzy. I think it is useful to give you more possibilities than you might expect. The returned terms are ordered according to a rank score from the text indexer.

**Comment by wdahdul** [comment]
That makes sense as the intended feature. Thanks.
