### ISSUE TITLE
Add context to taxon name display

### ISSUE THREAD

**Issue by balhoff** [phenoscape/phenoscape-kb-ui#4]
It is a challenge for users when the result contains a long list of obscure taxon names. We need a way to provide some context. One idea is to also display a common name and the containing taxonomic order. This has a couple of issues though. We have common names for many fish but not other taxa. Also, currently VTO does not really distinguish common name from other related synonyms (which may be outdated taxonomic names). And especially, since semantic similarity is returning higher level taxa, these will often be at or above the order rank.

**Comment by balhoff** [comment]
One option is to have someone provide general labels for some comprehensive and disjoint collection of upper level groups in the VTO. We can add these with a specific annotation property and display them:
Diplodoselachidae (shark)
Eigenmanniidae (bony fish)
Microdevario (bony fish)
Pangio (bony fish)
Squaliformes (shark)
Lepidobatrachus (amphibian)
Haplorrhini (mammal)

What do you think @tjv @prashanti @hlapp @pmabee?

**Comment by hlapp** [comment]
Nice idea, and worth trying!

**Comment by balhoff** [comment]
@pmabee would you have in mind a list of group names at the "right" level that would subsume all taxa in VTO but be non-overlapping? I could do the actual editing of the ontology part.

**Comment by balhoff** [comment]
This is now live, you can see the phylopics in the semantic similarity result list.
