### ISSUE TITLE
Anatomical entities showing up as a child of its own term

### ISSUE THREAD

**Issue by laurajackson** [phenoscape/phenoscape-kb-ui#43]
When I search a term in the KB (i.e., pectoral fin), I get pectoral fin as a child term of itself. Both terms ('pectoral fin' as parent and child) have different IDs, the parent term has UBERON:0000151, and the child 'pectoral fin' term has obo:ZFA_0001161 as the ID.

This seems to be the case for all terms I have tried in the KB.

**Comment by balhoff** [comment]
This is a duplicate of #38.
