### ISSUE TITLE
Display original character text for phenotypes

### ISSUE THREAD

**Issue by prashanti** [phenoscape/phenoscape-kb-ui#45]
Users need to be able to see original character text for phenotypes whether it be in the variation profile or directly associated phenotypes to taxa or in the detailed semantic similarity interface.  

In all of the above scenarios, it is beneficial to show both free text and OWL expressions and somehow let the user switch back and forth between the two. 

The same design can then be re-used for all instances where both character text and OWL expressions need to be shown. Also need to figure out a way to address the problem of seemingly redundant annotation comparison pairs in the detailed semantic similarity interface when character text is displayed.

**Comment by balhoff** [comment]
This should be the case everywhere now.
