### ISSUE TITLE
Display label for post-composed terms

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-ui#48]
On anatomy pages, the labels for postcomps are not being displayed (see screenshot)

![screen shot 2015-06-23 at 1 56 00 pm](https://cloud.githubusercontent.com/assets/957012/8317098/f634cb68-19af-11e5-9b94-da7487588ae3.png)

**Comment by balhoff** [comment]
@wdahdul I updated the classification service to hide unlabelled terms. So now only "real" ontology terms should show up in that view. Please close if this sounds okay to you.
