### ISSUE TITLE
Load additional pages of semantic similarity results

### ISSUE THREAD

**Issue by balhoff** [phenoscape/phenoscape-kb-ui#5]
Currently only the top 20 matches are shown. Need to add navigator buttons for additional results.

**Comment by balhoff** [comment]
This has been implemented in a preliminary way in 028f89962af5e4ecc599c407cf942fa7b7ad210a. However the web service query to get the corpus size is too slow, so an extra large total of 1000 is hardcoded.

**Comment by prashanti** [comment]
Done.
