### ISSUE TITLE
Extend anatomy term view to include part of and develops from

### ISSUE THREAD

**Issue by pmabee** [phenoscape/phenoscape-kb-ui#51]
Anatomy term view (classification) shows only subtypes, not parts.  Old KB view was much more informative, see: http://fish.phenoscape.org/term/entity/VSAO:0000154 vs. new: http://kb.phenoscape.org/#/entity/http://purl.obolibrary.org/obo/UBERON_0010711.  We don't want to recapitulate the full ontology view, but we need to see part_of and develops_from.

**Comment by balhoff** [comment]
I've added these relationships in the Classification tab. E.g.:

http://kb.phenoscape.org/#/entity/http://purl.obolibrary.org/obo/UBERON_0001685
