### ISSUE TITLE
Pop-up boxes for Anatomy, Taxa, Genes, need 'close' option

### ISSUE THREAD

**Issue by pmabee** [phenoscape/phenoscape-kb-ui#53]
User needs to be able to close expanded boxes.  Even when they don't intersect with text, they feel intrusive.  Search 'Cyprinella' and go to 'Phenotypes' tab.  The 'Genes' section of the pop-down covers up the Ontology Annotations.

**Comment by balhoff** [comment]
@pmabee for now, click the X to the right of the search box. I will look for ways to improve.

**Comment by wdahdul** [comment]
From Wasila and Paula: This issue still stands (related to #89)

**Comment by wdahdul** [comment]
Fixed in #89
