### ISSUE TITLE
Need to indicate whether a species has phenotype data in 'Classification' tab

### ISSUE THREAD

**Issue by pmabee** [phenoscape/phenoscape-kb-ui#54]
User looking for phenotypes for Cyprinella species.  Classification tab shows species list and user can see from label on 'Phenotypes' tab that there are 154 phenotypes.  But User cannot figure out which species has phenotype data without clicking on each one of them and looking at the number on the Phenotypes tab.

**Comment by balhoff** [comment]
@pmabee what do you think should be displayed? The number of phenotypes annotated to the displayed taxon? Or a total number for the phenotypes annotated to any taxon contained within the given taxon? (if the name is for a family for example, it may not have any annotated phenotypes but it may have some species that each have some phenotypes). Or number of taxa within that group with some data?

**Comment by wdahdul** [comment]
From Paula and Wasila: In the fish KB from faceted view, for taxa we displayed on the left side the phenotype count. Please use the same method of computing the phenotype count for this information to be displayed in the classification tab.

**Comment by balhoff** [comment]
Implemented in faceted browsing.
