### ISSUE TITLE
Hide zfin ID next to gene name

### ISSUE THREAD

**Issue by pmabee** [phenoscape/phenoscape-kb-ui#56]
User enters gene, e.g., oc90.  This appears: Gene oc90 (zebrafish) http://zfin.org/ZDB-GENE-070912-300.  The link 'http://zfin.org/ZDB-GENE-070912-300' is distracting -- can't we just link the gene symbol to it directly?

**Comment by balhoff** [comment]
Do you want to hide IDs for all types of terms? e.g. Uberon anatomy terms. ZFIN shows the ID for this gene at the top of the page:
http://zfin.org/ZDB-GENE-070912-300

**Comment by balhoff** [comment]
I updated these to shorten them with a prefix, e.g. ZFIN:ZDB-GENE-070912-300

**Comment by balhoff** [comment]
I am going to close this for now. Please reopen if you have additional thoughts on how IDs are displayed around the UI.
