### ISSUE TITLE
Redundancies in variation profile of taxa

### ISSUE THREAD

**Issue by prashanti** [phenoscape/phenoscape-kb-ui#58]
We need to remove repetitions in the variation profile as displayed on the KB. Example: http://kb.phenoscape.org/#/taxon/http://purl.obolibrary.org/obo/VTO_0001468?tab=variation

**Comment by prashanti** [comment]
When I queried the KB for profile sizes, I see that the profile size of Anaspida is 4. But, the KB displays 6 (with redundancies) and 5 (without redundancies). Why is there a discrepancy in the numbers? http://kb.phenoscape.org/#/taxon/http://purl.obolibrary.org/obo/VTO_9030507?tab=variation

**Comment by balhoff** [comment]
@prashanti where did you get the "4"? I updated the taxon page to show the character state description and ontology annotation, so the redundancy makes more sense now.
