### ISSUE TITLE
unexpected search results

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-ui#63]
The search results for a query on 'fin' lists terms, many limb ones, that seem unrelated to fin:

manual digit
fin
nail of manual digit
distal segment of manual digit
epidermal ridge of digit
fin fold pectoral fin bud
pectoral fin
pelvic fin
phalanx of manus
manual digit 1
paired fin bud
paired fin
dorsal fin
digit nerve of manus
manual digit skin
manual digit 2
manual digit 3
manual digit 4
manual digit 5
manual digit bone

**Comment by hlapp** [comment]
These are parts of homologs of paired fin. (I thought we don't yet have the homology assertions in the regular KB but perhaps I'm mistaken.)

**Comment by wdahdul** [comment]
It would be less confusing if the results were organized with homologous parts separated from the ontology matches to 'fin'. Perhaps first list alphabetically the matches to 'fin', including child terms, then list the homologous part.s

**Comment by balhoff** [comment]
New order:
fin
fin fold
pectoral fin bud
dorsal fin
paired fin
paired fin bud
pectoral fin
pelvic fin
digit nerve of manus
distal segment of manual digit
epidermal ridge of digit
manual digit
manual digit 1
manual digit 2
manual digit 3
manual digit 4
manual digit 5
manual digit bone
manual digit skin
nail of manual digit
phalanx of manus

**Comment by balhoff** [comment]
You can try it online.
