### ISSUE TITLE
How to find annotations for a phenotype

### ISSUE THREAD

**Issue by hlapp** [phenoscape/phenoscape-kb-ui#66]
I have the following character state: _vomer articulates anteriorly with the mesethmoid; vomer has a vertical or oblique synchondral joint with the mesethmoid._ I want to find out how this character state is annotated in the KB, but answering this question seems very difficult or even impossible.

I was able to find the annotation for _vomer extends anteroventral to the mesethmoid_ (which quite oddly is `horizontal and (inheres in some mesethmoid-vomer joint)`), but only because I happened to have a taxon that has this state ([Notogoneus osculus](http://kb.phenoscape.org/#/taxon/http://purl.obolibrary.org/obo/VTO_0066303)), and because "v" is near the end of the alphabet and so I could quickly page to the end of the very long list of character state annotations for this taxon. Otherwise one seems to be out of luck.

**Comment by pmabee** [comment]
Actually there is no way to even see a list of vomer phenotypes (if a user began with 'vomer').  This is a major priority -- exposing phenotype data....

**Comment by wdahdul** [comment]
Implementing #77 would solve this issue.
