### ISSUE TITLE
Search not working for 'skeletal element of eye region'

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-ui#67]
Can't seem to search directly for this term: 'skeletal element of eye region'.  Other similar terms give list of results (e.g., 'skeletal element', 'eye region') but not when searching by the complete term name.

**Comment by balhoff** [comment]
That's really strange. I will investigate.

**Comment by wdahdul** [comment]
same issue with 'neck of rib' and 'neck of radius'. I'm thinking the search is tripping on 'of' in these labels.

**Comment by balhoff** [comment]
Yes, I think it is an issue with "stopwords" used by the text analyzer in Blazegraph. I am trying to figure out how to treat stop words as normal words.

**Comment by balhoff** [comment]
Disabling stopwords in Blazegraph requires setting these properties in the config file:

``` INI
com.bigdata.search.FullTextIndex.analyzerFactoryClass=com.bigdata.search.ConfigurableAnalyzerFactory
com.bigdata.search.ConfigurableAnalyzerFactory.analyzer.eng.analyzerClass=org.apache.lucene.analysis.standard.StandardAnalyzer
com.bigdata.search.ConfigurableAnalyzerFactory.analyzer.eng.stopwords=none
com.bigdata.search.ConfigurableAnalyzerFactory.analyzer._.like=eng
```

**Comment by balhoff** [comment]
The new Blazegraph configuration is deployed now, and this is working.
