### ISSUE TITLE
Ontotrace supporting states

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-ui#70]
Currently the version of matrix downloaded from ontotrace doesn't contain the supporting text and sources for each character. Would like the option of obtaining this.

**Comment by balhoff** [comment]
Including these makes the output files prohibitively large (and also makes the query slower). What do you think about a little panel in Phenex that has a button/link that opens this page in your browser, with the right taxon and structure filled in depending on which matrix cell you've selected?

http://kb.phenoscape.org/#/taxon/http://purl.obolibrary.org/obo/VTO_9001290?tab=phenotypes&phenotypes.quality_type=entailing-absence&phenotypes.entity=http:%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_2000250

**Comment by wdahdul** [comment]
Yes, I think that's a good solution to view the source info.

**Comment by balhoff** [comment]
This panel is now available in Phenex 1.17. It is called "Supporting States in the Phenoscape KB".
