### ISSUE TITLE
Update data downloads for phenotypes to return plain text

### ISSUE THREAD

**Issue by balhoff** [phenoscape/phenoscape-kb-ui#71]
Recently added downloads for phenotype profiles are being delivered as JSON instead of plain text.

**Comment by balhoff** [comment]
Fixed by https://github.com/phenoscape/phenoscape-kb-services/commit/750335bfb6b531682b207a73bfbf24fc7e1ab01e

**Comment by hlapp** [comment]
This looks like `text/tab-separated-values` and `application/json` as requested media types are being treated with the same response (which doesn't sound right). Am I misreading the diff?

**Comment by balhoff** [comment]
"Marshallers" are used to convert from a rich object (`Seq[AnnotatedCharacterDescription]`) to a serialization format. To handle multiple serialization formats you need to combine multiple marshallers into one, which happens on this line:
https://github.com/phenoscape/phenoscape-kb-services/commit/750335bfb6b531682b207a73bfbf24fc7e1ab01e#diff-c9510d38adf084f230cf99767a5ae538R259

That marshaller is the one used by the framework to handle the response.
