### ISSUE TITLE
Provide information on how to contribute data

### ISSUE THREAD

**Issue by balhoff** [phenoscape/phenoscape-kb-ui#74]
The Phenoscape site doesn't really invite anyone to contribute annotations.

**Comment by pmabee** [comment]
Suggestion to add text "Contribute data" on right-hand side of main KB page (http://kb.phenoscape.org/#/home) below "Data API", and link to this page: http://wiki.phenoscape.org/wiki/Resources_for_curators

**Comment by wdahdul** [comment]
Here is the updated URL for the "contribute data" link: http://wiki.phenoscape.org/wiki/Resources_for_Data_Contributors

**Comment by balhoff** [comment]
@pmabee @wdahdul please review the new text under "Contribute data" on the homepage: http://kb.phenoscape.org/#/home

**Comment by wdahdul** [comment]
+1
