### ISSUE TITLE
Clean up search options on anatomy term page

### ISSUE THREAD

**Issue by balhoff** [phenoscape/phenoscape-kb-ui#76]
Taxa with phenotypes search is missing "parts" checkbox.

Genes with phenotypes search is missing "quality" filter. Should also add model organism filter.

**Comment by balhoff** [comment]
Taxon for "entity parts" is implemented. The other two are still pending.

**Comment by balhoff** [comment]
Added quality filter for genes in 8fb3066baaeebca8669d0b7c4e20923cfe085474.

**Comment by wdahdul** [comment]
This is mostly implemented now. The model organism filter will be added to faceted browsing.
