### ISSUE TITLE
Add phenotypes tab to anatomy term page

### ISSUE THREAD

**Issue by balhoff** [phenoscape/phenoscape-kb-ui#77]
A top level tab could list a search result for phenotype classes. There are some issues to consider, since the phenotype hierarchy is huge. Perhaps only phenotypes used in annotations should be returned.

cc @wdahdul

**Comment by balhoff** [comment]
Not sure if this is still requested—review after implementing top priority issues including phenotype pop-up.

**Comment by wdahdul** [comment]
Not needed (see current ui mockups)
