### ISSUE TITLE
Add OTU label column to study taxon list

### ISSUE THREAD

**Issue by balhoff** [phenoscape/phenoscape-kb-ui#80]
This is to show the name used in the publication before annotating with a VTO term.

**Comment by wdahdul** [comment]
Closing this, doesn't seem to be a priority.

**Comment by hlapp** [comment]
Could I ask that we don't close low-priority issues but instead label them as low priority? That way we don't lose the record of these still being in principle desirable enhancements.

If they are obsolete or indeed no longer desirable, then do close.

**Comment by wdahdul** [comment]
Sorry, we meant that this is no longer a desirable feature. Will close it again.
