### ISSUE TITLE
Add ontology annotation column to study phenotype list

### ISSUE THREAD

**Issue by balhoff** [phenoscape/phenoscape-kb-ui#81]

**Comment by pmabee** [comment]
Currently (4 June 2016) we see ontology annotation in the popup box.  We had discussed a way for users to toggle between free txt vs. phenotype annotations.  

http://kb.phenoscape.org/#/study/http://dx.doi.org/10.1111/j.1096-3642.2008.00407.x

**Comment by wdahdul** [comment]
Closing; see mockups for current ideas.
