### ISSUE TITLE
Add search filters to taxon and phenotype listings on study page.

### ISSUE THREAD

**Issue by balhoff** [phenoscape/phenoscape-kb-ui#82]

**Comment by pmabee** [comment]
Study page = publication page, e.g., http://kb.phenoscape.org/#/study/http://dx.doi.org/10.1111/j.1096-3642.2008.00407.x .

**Comment by pmabee** [comment]
Wasila and I don't think that adding search filters to the study (publication) page is important, so we are closing this.

**Comment by wdahdul** [comment]
Closing because this feature is no longer desired.
