### ISSUE TITLE
Rename classification tab 

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-ui#84]
Suggestion to rename it as "Properties" to be more informative about content of this tab

**Comment by balhoff** [comment]
@wdahdul made the change:

http://phenoscape.github.io/phenoscape-kb-ui/#/entity/http://purl.obolibrary.org/obo/UBERON_0002513?tab=properties&taxatab=phenotypes&genestab=phenotypes

http://phenoscape.github.io/phenoscape-kb-ui/#/taxon/http://purl.obolibrary.org/obo/VTO_0039086?phenotypes.quality_type=quality-phenotype&tab=properties

**Comment by wdahdul** [comment]
+1
