### ISSUE TITLE
Anatomy term Definition display

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-ui#85]
Add "Definition:" prior to a term's definition on the anatomy page

**Comment by balhoff** [comment]
@wdahdul added: http://phenoscape.github.io/phenoscape-kb-ui/#/entity/http://purl.obolibrary.org/obo/UBERON_0002513?tab=taxa&taxatab=phenotypes&genestab=phenotypes

**Comment by wdahdul** [comment]
+1
