### ISSUE TITLE
Move subtype information to relationships list in classification panel

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-ui#88]
The is_a term classification heirarchy to the left of the panel is better placed with the other relationships to the right.

**Comment by balhoff** [comment]
But you want to replace the hierarchy with the full ontology tree, correct?

**Comment by wdahdul** [comment]
Yes, replacing the hierarchy with the full ontology tree view on the left. The right contains the summary of relationships in text form.

**Comment by balhoff** [comment]
Covered by #100.
