### ISSUE TITLE
Add taxon icons to Taxon list in results

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-ui#92]
In the Taxon tab, add animal icons to first column to help users visually comprehend taxon results

**Comment by balhoff** [comment]
@wdahdul ready to review: http://phenoscape.github.io/phenoscape-kb-ui/#/entity/http://purl.obolibrary.org/obo/UBERON_0002513?tab=taxa&taxatab=phenotypes&genestab=phenotypes

**Comment by wdahdul** [comment]
+1! Looks good.
