### ISSUE TITLE
Add term pop-up box when clicking on ontology term

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-ui#93]
Currently when a user clicks on a taxon name in the taxon tab, the link goes to a separate page for that taxon, sometimes causing confusion about what originally led the user to the new page. 

Instead, add a pop-up box with term information (source ontology, ID, definition, relations, etc...) and links to the taxon page in the KB. This is similar to the behavior in the old fish KB.

Also applies to anatomy terms

**Comment by balhoff** [comment]
Implemented.
