### ISSUE TITLE
Display phenotypes rather than "view phenotypes" link

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-ui#94]
It will be more informative to display actual phenotypes on the results page rather than having user click on the "view phenotypes" link to the separate page to view phenotypes.

Related, where there is more than one phenotype for a taxon, just display the first, and add a "view more" or "show all 3 phenotypes" expansion link that when clicked will show the other phenotypes

Jim, regarding your emailed question: "Do you mean you just want all the taxa listed redundantly, with a row for each taxon + phenotype (display annotations, rather than taxa). Or do you want to click and expand the single row to see a little list of phenotypes for that taxon in place? For more general terms there could be quite a few phenotypes associated with the taxon."

We were thinking of the latter (click and expand the single row to see a list of phenotypes for that single taxon).

**Comment by balhoff** [comment]
When downloading results, one could either download the list of taxa (like now) or download the list of taxon by phenotype annotations (which would be like if you expanded the "show phenotypes" cell for every row and made a new row for each taxon+phenotype pair).

**Comment by balhoff** [comment]
Addressed by faceted browsing view.
