### ISSUE TITLE
"Feedback" link to tracker on KB pages

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-ui#95]
Please add a link on each page of the KB to the UI tracker - will be helpful when users want to give feedback.

**Comment by wdahdul** [comment]
Can be simple like the "feedback" button in the old KB

**Comment by balhoff** [comment]
@wdahdul ready to review: http://phenoscape.github.io/phenoscape-kb-ui/#/home

**Comment by wdahdul** [comment]
+1
