### ISSUE TITLE
Move link to newick tree from Misc tab to Classification tab

### ISSUE THREAD

**Issue by wdahdul** [phenoscape/phenoscape-kb-ui#97]
On the taxon pages, the link to download a newick tree would be better placed in the Classification tab, rather than in Misc. Can also get rid of the Misc tab which isn't informatively named.

**Comment by balhoff** [comment]
@wdahdul this is ready for review: http://phenoscape.github.io/phenoscape-kb-ui/#/taxon/http://purl.obolibrary.org/obo/VTO_0036216?phenotypes.quality_type=quality-phenotype&tab=classification

Just respond with a comment for modifications, or even just "+1" if you think the change is satisfactory. Then I'll make further changes or merge into release. I'll be tagging issues that are ready to check on the beta site with the [review](https://github.com/phenoscape/phenoscape-kb-ui/labels/review) label.

**Comment by wdahdul** [comment]
+1

**Comment by balhoff** [comment]
Fixed by f45f5ab352908b1c539597c75b26803239fdb26f.
